[package]
name = "pallet-storage-providers"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
sp-core = { version = "3.0", default-features = false }
sp-std = { version = "3.0", default-features = false }
frame-support = { version = "3.0", default-features = false }
frame-system = { version = "3.0", default-features = false }

# Add other dependencies specific to your pallet

[features]
default = ["std"]
std = [
    "sp-core/std",
    "sp-std/std",
    "frame-support/std",
    "frame-system/std",
]

[workspace]
members = [
    "pallet",
    # Add other related crates or modules here
]