[package]
name = "selendra-node-subsystem-types"
version = "0.9.13"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
description = "Subsystem traits and message definitions"

[dependencies]
futures = "0.3.21"
selendra-node-jaeger = { path = "../jaeger" }
selendra-overseer-gen = { path = "../overseer/overseer-gen" }
sc-network = { git = "https://github.com/paritytech/substrate", rev = "c364008a6c7da8456e17967f55edf51e45146998" }
sp-runtime = { git = "https://github.com/paritytech/substrate", rev = "c364008a6c7da8456e17967f55edf51e45146998" }
smallvec = "1.8.0"
substrate-prometheus-endpoint = { git = "https://github.com/paritytech/substrate", rev = "c364008a6c7da8456e17967f55edf51e45146998" }
thiserror = "1.0.30"

neak-node-primitives = { path = "../../../primitives/neak-node" }
kp-executor = { path = "../../../primitives/executor" }
kumandra-core-primitives = { path = "../../../primitives/core" }
kumandra-runtime-primitives = { path = "../../../primitives" }
