[package]
name = "pallet-segment-book"
version = "0.1.0"
authors = ["Kumandra"]
edition = "2018"
license = "Apache-2.0"
repository = ""
description = "FRAME pallet for segment management"
readme = "README.md"

[dependencies]
serde = { version = "1.0.101", optional = true }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
scale-info = { default-features = false, features = ['derive'], version = "1.0" }

frame-benchmarking = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10', default-features = false, optional = true }
frame-support = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10', default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10', default-features = false }

sp-io = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10', default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10', default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10', default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10', default-features = false }

pallet-balances = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10', default-features = false }
pallet-sminer = { path = '../sminer', default-features = false }

[dev-dependencies]
pallet-timestamp = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
frame-support-test = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
pallet-scheduler = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"serde",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"frame-benchmarking/std",
]
runtime-benchmarks = ["frame-benchmarking"]
