[package]
name = "selendra-overseer"
version = "0.9.13"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
client = { package = "sc-client-api", git = "https://github.com/paritytech/substrate", rev = "c364008a6c7da8456e17967f55edf51e45146998" }
sp-api = { git = "https://github.com/paritytech/substrate", rev = "c364008a6c7da8456e17967f55edf51e45146998" }
futures = "0.3.21"
futures-timer = "3.0.2"
parking_lot = "0.12.0"
selendra-node-subsystem-types = { path = "../subsystem-types" }
selendra-node-metrics = { path = "../metrics" }
selendra-overseer-gen = { path = "./overseer-gen" }
tracing = "0.1.32"
lru = "0.7.3"
parity-util-mem = { version = "0.11.0", default-features = false }

neak-node-primitives = { path = "../../../primitives/neak-node" }
kumandra-runtime-primitives = { path = "../../../primitives" }

[dev-dependencies]
metered-channel = { path = "../metered-channel" }
sp-core = { git = "https://github.com/paritytech/substrate", rev = "c364008a6c7da8456e17967f55edf51e45146998" }
futures = { version = "0.3.21", features = ["thread-pool"] }

[features]
default = []
