[package]
name = "kc-consensus-rpc"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>", "Kumandra <admin@kumandra.org>"]
description = "RPC extensions for the Kumandra consensus algorithm"
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://koompi.com"
repository = "https://github.com/kumandra/kumandra"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-oneshot = "0.5.0"
futures = "0.3.21"
futures-timer = "3.0.2"
jsonrpsee = { version = "0.14.0", features = ["server", "macros"] }
log = "0.4.17"
parity-scale-codec = "3.1.5"
parking_lot = "0.12.1"
sc-client-api = { version = "4.0.0-dev", git = "https://github.com/kumandra/substrate", rev = "1399afdcd8ab4d7fad149c96f9cadcaf04b94f86" }
kc-consensus = { version = "0.1.0", path = "../" }
sc-rpc = { version = "4.0.0-dev", git = "https://github.com/kumandra/substrate", rev = "1399afdcd8ab4d7fad149c96f9cadcaf04b94f86" }
sc-utils = { version = "4.0.0-dev", git = "https://github.com/kumandra/substrate", rev = "1399afdcd8ab4d7fad149c96f9cadcaf04b94f86" }
sp-api = { version = "4.0.0-dev", git = "https://github.com/kumandra/substrate", rev = "1399afdcd8ab4d7fad149c96f9cadcaf04b94f86" }
kp-consensus = { version = "0.1.0", path = "../../../primitives/consensus" }
sp-consensus-slots = { version = "0.10.0-dev", git = "https://github.com/kumandra/substrate", rev = "1399afdcd8ab4d7fad149c96f9cadcaf04b94f86" }
sp-blockchain = { version = "4.0.0-dev", git = "https://github.com/kumandra/substrate", rev = "1399afdcd8ab4d7fad149c96f9cadcaf04b94f86" }
sp-core = { version = "6.0.0", git = "https://github.com/kumandra/substrate", rev = "1399afdcd8ab4d7fad149c96f9cadcaf04b94f86" }
sp-runtime = { version = "6.0.0", git = "https://github.com/kumandra/substrate", rev = "1399afdcd8ab4d7fad149c96f9cadcaf04b94f86" }
kumandra-archiving = { version = "0.1.0", path = "../../../modules/archiving" }
kumandra-core-primitives = { version = "0.1.0", path = "../../../primitives/core" }
kumandra-rpc-primitives = { version = "0.1.0", path = "../../../primitives/rpc" }
