[package]
name = "kp-lightclient"
version = "0.1.0"
authors = ["Hangsia Hong <hangsiahong@kumandra.org>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://koompi.com"
repository = "https://github.com/kumandra/kumandra"
description = "Light client substrate primitives for Kumandra"
include = [
    "/src",
    "/Cargo.toml",
    "/README.md",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "3.1.2", default-features = false }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
schnorrkel = { version = "0.9.1", default-features = false, features = ["u64_backend"] }
sp-arithmetic = { version = "5.0.0", default-features = false, git = "https://github.com/kumandra/substrate", rev = "1399afdcd8ab4d7fad149c96f9cadcaf04b94f86" }
sp-consensus-slots = { version = "0.10.0-dev", default-features = false, git = "https://github.com/kumandra/substrate", rev = "1399afdcd8ab4d7fad149c96f9cadcaf04b94f86" }
kp-consensus = { version = "0.1.0", path = "../consensus", default-features = false }
sp-runtime = { version = "6.0.0", default-features = false, git = "https://github.com/kumandra/substrate", rev = "1399afdcd8ab4d7fad149c96f9cadcaf04b94f86" }
sp-std = { version = "4.0.0-dev", default-features = false, git = "https://github.com/kumandra/substrate", rev = "1399afdcd8ab4d7fad149c96f9cadcaf04b94f86" }
kumandra-core-primitives = { version = "0.1.0", path = "../core", default-features = false }
kumandra-solving = { version = "0.1.0", path = "../../modules/solving", default-features = false }
kumandra-verification = { version = "0.1.0", path = "../verification", default-features = false }

[dev-dependencies]
frame-support = { version = "4.0.0-dev", git = "https://github.com/kumandra/substrate", rev = "1399afdcd8ab4d7fad149c96f9cadcaf04b94f86" }
rand = { version = "0.8.5", features = ["min_const_gen"] }
kumandra-archiving = { version = "0.1.0", path = "../../modules/archiving"}

[features]
default = ["std"]
std = [
    "codec/std",
    "scale-info/std",
    "schnorrkel/std",
    "sp-arithmetic/std",
    "sp-consensus-slots/std",
    "kp-consensus/std",
    "sp-runtime/std",
    "sp-std/std",
    "kumandra-core-primitives/std",
    "kumandra-solving/std",
    "kumandra-verification/std"
]
