[package]
name = "kumandra-fraud-proof"
version = "0.1.0"
authors = ["Liu-Cheng Xu <xuliuchengxlc@gmail.com>", "Hangsia Hong <hangsiahong@gmail.com>"]
edition = "2021"
license = "GPL-3.0-or-later"
homepage = "https://koompi.com"
repository = "https://github.com/kumandra/kumandra/"
description = "Kumandra fraud proof utilities"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.1.5", features = ["derive"] }
hash-db = "0.15.2"
sc-client-api = { version = "4.0.0-dev", git = "https://github.com/kumandra/substrate", rev = "1399afdcd8ab4d7fad149c96f9cadcaf04b94f86" }
sp-api = { version = "4.0.0-dev", git = "https://github.com/kumandra/substrate", rev = "1399afdcd8ab4d7fad149c96f9cadcaf04b94f86" }
sp-blockchain = { version = "4.0.0-dev", git = "https://github.com/kumandra/substrate", rev = "1399afdcd8ab4d7fad149c96f9cadcaf04b94f86" }
sp-core = { version = "6.0.0", git = "https://github.com/kumandra/substrate", rev = "1399afdcd8ab4d7fad149c96f9cadcaf04b94f86" }
kp-executor = { version = "0.1.0", path = "../../primitives/executor" }
sp-runtime = { version = "6.0.0", git = "https://github.com/kumandra/substrate", rev = "1399afdcd8ab4d7fad149c96f9cadcaf04b94f86" }
sp-state-machine = { version = "0.12.0", git = "https://github.com/kumandra/substrate", rev = "1399afdcd8ab4d7fad149c96f9cadcaf04b94f86" }
sp-trie = { version = "6.0.0", git = "https://github.com/kumandra/substrate", rev = "1399afdcd8ab4d7fad149c96f9cadcaf04b94f86" }
tracing = "0.1.35"

[dev-dependencies]
cirrus-block-builder = { version = "0.1.0", path = "../../cumulus/client/block-builder" }
cirrus-primitives = { version = "0.1.0", path = "../../cumulus/primitives" }
cirrus-test-service = { version = "0.1.0", path = "../../cumulus/test/service" }
futures = "0.3.21"
pallet-balances = { version = "4.0.0-dev", git = "https://github.com/kumandra/substrate", rev = "1399afdcd8ab4d7fad149c96f9cadcaf04b94f86" }
sc-cli = { version = "0.10.0-dev", git = "https://github.com/kumandra/substrate", rev = "1399afdcd8ab4d7fad149c96f9cadcaf04b94f86", default-features = false }
sc-service = { version = "0.10.0-dev", git = "https://github.com/kumandra/substrate", rev = "1399afdcd8ab4d7fad149c96f9cadcaf04b94f86", default-features = false }
sp-keyring = { version = "6.0.0", git = "https://github.com/kumandra/substrate", rev = "1399afdcd8ab4d7fad149c96f9cadcaf04b94f86" }
substrate-test-utils = { version = "4.0.0-dev", git = "https://github.com/kumandra/substrate", rev = "1399afdcd8ab4d7fad149c96f9cadcaf04b94f86" }
tokio = "1.20.0"
