[package]
name = "kumandra-rpc-primitives"
version = "0.1.0"
authors = ["Kumandra"]
description = "RPC primitives for Kumandra Network"
edition = "2021"
license = "Apache-2.0"
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
hex-buffer-serde = "0.3.0"
serde = { version = "1.0.136", features = ["derive"] }
kumandra-core-primitives = { version = "0.1.0", path = "../core" }