[package]
name = "kumandra-rpc-primitives"
version = "0.1.0"
authors = ["Kumandra <admin@kuamndra.org>"]
description = "RPC primitives for Kumandra Network"
edition = "2021"
license = "Apache-2.0"
homepage = "https://kumandra.org"
repository = "https://github.com/kumandra/kumandra"
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
hex = { version = "0.4.3", features = ["serde"] }
serde = { version = "1.0.139", features = ["derive"] }
kumandra-core-primitives = { version = "0.1.0", path = "../core" }
