[package]
name = "kc-consensus-rpc"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>", "Subspace Labs <admin@subspace.network>", "Kumandrian <kumandrian@koompi.com"]
description = "RPC extensions for the Kumandra consensus algorithm"
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-oneshot = "0.5.0"
futures = "0.3.21"
futures-timer = "3.0.2"
jsonrpsee = { version = "0.14.0", features = ["server", "macros"] }
log = "0.4.17"
parity-scale-codec = "3.1.2"
parking_lot = "0.12.0"
sc-client-api = { version = "4.0.0-dev", git = "https://github.com/kumandra/substrate", rev = "b49d8ee54f4bd6e4b5b48f45d08f75705fad95b4" }
kc-consensus = { version = "0.1.0", path = "../" }
sc-rpc = { version = "4.0.0-dev", git = "https://github.com/kumandra/substrate", rev = "b49d8ee54f4bd6e4b5b48f45d08f75705fad95b4" }
sc-utils = { version = "4.0.0-dev", git = "https://github.com/kumandra/substrate", rev = "b49d8ee54f4bd6e4b5b48f45d08f75705fad95b4" }
sp-api = { version = "4.0.0-dev", git = "https://github.com/kumandra/substrate", rev = "b49d8ee54f4bd6e4b5b48f45d08f75705fad95b4" }
kp-consensus = { version = "0.1.0", path = "../../../../primitives/consensus" }
sp-consensus-slots = { version = "0.10.0-dev", git = "https://github.com/kumandra/substrate", rev = "b49d8ee54f4bd6e4b5b48f45d08f75705fad95b4" }
sp-blockchain = { version = "4.0.0-dev", git = "https://github.com/kumandra/substrate", rev = "b49d8ee54f4bd6e4b5b48f45d08f75705fad95b4" }
sp-core = { version = "6.0.0", git = "https://github.com/kumandra/substrate", rev = "b49d8ee54f4bd6e4b5b48f45d08f75705fad95b4" }
sp-runtime = { version = "6.0.0", git = "https://github.com/kumandra/substrate", rev = "b49d8ee54f4bd6e4b5b48f45d08f75705fad95b4" }
kumandra-archiving = { version = "0.1.0", path = "../../../../modules/archiving" }
kumandra-core-primitives = { version = "0.1.0", path = "../../../../primitives/core" }
kumandra-rpc-primitives = { version = "0.1.0", path = "../../../../primitives/rpc" }
