[package]
name = 'kumandra-node'
version = '0.1.0'
authors = ['Kumandra']
build = 'build.rs'
description = 'A fresh FRAME-based Substrate node, ready for hacking.'
edition = '2018'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[[bin]]
name = 'kumandra'
path = "src/main.rs"

[dependencies]
jsonrpc-core = '18.0.0'
structopt = '0.3.8'
rand = "0.7.2"

sc-basic-authorship = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sc-cli = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10', features = ['wasmtime'] }
sc-client-api = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sc-consensus = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sc-executor = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10', features = ['wasmtime'] }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sc-keystore = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sc-rpc = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sc-rpc-api = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sc-service = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10', features = ['wasmtime'] }
sc-telemetry = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sc-transaction-pool-api = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sc-consensus-uncles = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sc-finality-grandpa-rpc = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sc-consensus-babe-rpc = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sc-consensus-epochs = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }

sp-api  = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sp-block-builder = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sp-blockchain = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sp-consensus = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sp-core = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sp-runtime = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sp-timestamp = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sp-transaction-storage-proof = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sp-authorship = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sp-keystore = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }

frame-benchmarking = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }

pallet-im-online = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
pallet-contracts = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
pallet-contracts-rpc = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }

kumandra-runtime = { path = '../runtime' }

substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }

[features]
default = []
runtime-benchmarks = ['kumandra-runtime/runtime-benchmarks']
