[package]
name = "selendra-node-subsystem-util"
version = "0.9.13"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
description = "Subsystem traits and message definitions"

[dependencies]
async-trait = "0.1.52"
futures = "0.3.21"
pin-project = "1.0.10"
thiserror = "1.0.30"
tracing = "0.1.32"

selendra-node-subsystem = { package = "selendra-node-subsystem", path = "../subsystem" }
selendra-node-jaeger = { path = "../jaeger" }
selendra-node-metrics = { path = "../metrics" }
selendra-overseer = { path = "../overseer" }
metered-channel = { path = "../metered-channel" }

sp-core = { git = "https://github.com/paritytech/substrate", rev = "c364008a6c7da8456e17967f55edf51e45146998" }
sp-runtime = { git = "https://github.com/paritytech/substrate", rev = "c364008a6c7da8456e17967f55edf51e45146998" }

kp-executor = { path = "../../../primitives/executor" }
kumandra-core-primitives = { path = "../../../primitives/core" }
kumandra-runtime-primitives = { path = "../../../primitives" }
